import { Piece } from "../Interfaces";

export enum Files {
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
}

export declare type FileType = keyof typeof Files;

export enum PieceValues {
    pawn = 1,
    knight = 3,
    // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
    bishop = 3,
    rook = 5,
    queen = 9,
}

export const initialPositions = {
    a8: <Piece>{ color: "black", name: "rook", code: "R" },
    b8: <Piece>{ color: "black", name: "knight", code: "N" },
    c8: <Piece>{ color: "black", name: "bishop", code: "B" },
    d8: <Piece>{ color: "black", name: "queen", code: "Q" },
    e8: <Piece>{ color: "black", name: "king", code: "K" },
    f8: <Piece>{ color: "black", name: "bishop", code: "B" },
    g8: <Piece>{ color: "black", name: "knight", code: "N" },
    h8: <Piece>{ color: "black", name: "rook", code: "R" },
    a7: <Piece>{ color: "black", name: "pawn", code: "P" },
    b7: <Piece>{ color: "black", name: "pawn", code: "P" },
    c7: <Piece>{ color: "black", name: "pawn", code: "P" },
    d7: <Piece>{ color: "black", name: "pawn", code: "P" },
    e7: <Piece>{ color: "black", name: "pawn", code: "P" },
    f7: <Piece>{ color: "black", name: "pawn", code: "P" },
    g7: <Piece>{ color: "black", name: "pawn", code: "P" },
    h7: <Piece>{ color: "black", name: "pawn", code: "P" },
    a6: null,
    b6: null,
    c6: null,
    d6: null,
    e6: null,
    f6: null,
    g6: null,
    h6: null,
    a5: null,
    b5: null,
    c5: null,
    d5: null,
    e5: null,
    f5: null,
    g5: null,
    h5: null,
    a4: null,
    b4: null,
    c4: null,
    d4: null,
    e4: null,
    f4: null,
    g4: null,
    h4: null,
    a3: null,
    b3: null,
    c3: null,
    d3: null,
    e3: null,
    f3: null,
    g3: null,
    h3: null,
    a2: <Piece>{ color: "white", name: "pawn", code: "P" },
    b2: <Piece>{ color: "white", name: "pawn", code: "P" },
    c2: <Piece>{ color: "white", name: "pawn", code: "P" },
    d2: <Piece>{ color: "white", name: "pawn", code: "P" },
    e2: <Piece>{ color: "white", name: "pawn", code: "P" },
    f2: <Piece>{ color: "white", name: "pawn", code: "P" },
    g2: <Piece>{ color: "white", name: "pawn", code: "P" },
    h2: <Piece>{ color: "white", name: "pawn", code: "P" },
    a1: <Piece>{ color: "white", name: "rook", code: "R" },
    b1: <Piece>{ color: "white", name: "knight", code: "N" },
    c1: <Piece>{ color: "white", name: "bishop", code: "B" },
    d1: <Piece>{ color: "white", name: "queen", code: "Q" },
    e1: <Piece>{ color: "white", name: "king", code: "K" },
    f1: <Piece>{ color: "white", name: "bishop", code: "B" },
    g1: <Piece>{ color: "white", name: "knight", code: "N" },
    h1: <Piece>{ color: "white", name: "rook", code: "R" },
};
